apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: justcalm
spec:
  version: 7.6.2
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2G
                limits:
                  memory: 3G
          initContainers:
            - name: init-myservice
              image: busybox:1.28
              securityContext:
                privileged: true
              command: 
                - "sysctl"
                - "-w"
                - "vm.max_map_count=262144"
