apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: justcalm
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: justcalm
  http:
    tls:
      selfSignedCertificate:
        disabled: true
