apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: kibana-ingress
spec:
    rules:
        - host: kibana.justcalm.ink
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: kibana-kibana
                        servicePort: 5601
