apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: kibana-ingress
spec:
    rules:
        - host: kibana.kube.justcalm.ink
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: justcalm-kb-http
                        servicePort: 5601
