apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-mongo
  labels:
    type: local
    function: rocketchat
    unit: mongo
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pvs/rocketchat-mongo"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-data
  labels:
    type: local
    function: rocketchat
    unit: data
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pvs/rocketchat-data"
