apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-rocketchat
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-rocketchat-v2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-rocketchat-v1"
