apiVersion: v1
kind: Service
metadata:
    name: jenkins
    labels:
        app: jenkins
spec:
    selector:
        app: jenkins
    ports:
        - port: 80
          targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: jenkins
spec:
    selector:
        matchLabels:
            app: jenkins
    serviceName: "jenkins"
    replicas: 1
    template:
        metadata:
            labels:
                app: jenkins
        spec:
            containers:
                - name: jenkins
                  image: jenkins/jenkins:lts
                  ports:
                    - containerPort: 8080
                  volumeMounts:
                    - mountPath: "/var/jenkins_home"
                      name: "jenkins-pv-home"
            volumes:
                - name: jenkins-pv-home
                  persistentVolumeClaim:
                      claimName: jenkins-pvc-home
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: jenkins-ingress
spec:
    rules:
        - host: jenkins.kube.justcalm.ink
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: jenkins
                        servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-home
  labels:
    type: local
    function: jenkins
    unit: home
spec:
  storageClassName: standard
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
          storage: 10G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-home
  labels:
    type: local
    function: jenkins
    unit: home
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pvs/jenkins-home"
