apiVersion: v1
kind: Pod
metadata: 
    name: logstash
spec:
    containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.2.0
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
            - name: ca-cert
              mountPath: /usr/share/logstash/ca-certs
    volumes:
        - name: pipeline
          configMap:
            name: pipeline
        - name: ca-cert
          configMap:
            name: ca-cert
    dnsPolicy: Default
