apiVersion: v1
kind: Pod
metadata: 
    name: logstash
spec:
    containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.2.0
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline-
    initContainers:
        - name: cp
          image: busybox
          command: 
            - '/bin/sh'
            - '-c'
            - 'cp /config/*  /pipeline'
          volumeMounts:
            - name: pipeline
              mountPath: /pipeline
            - name: config-logstash
              mountPath: /config
    volumes:
        - name: config-logstash
          configMap:
            name: logstash-config
        - name: pipeline
    dnsPolicy: Default
